### ISSUE TITLE
BOM file

### ISSUE THREAD

**Issue by badass-boss** [aerobaticant/Greaseweazle-F7-Plus#1]
Where is the BOM file for this board?? I can't find it anywhere. Please reply. Thanks in advance

**Comment by sean-skt** [comment]
That's funny. I was just about the ask this question, when I logged in. I also just wanted to know, is it the BOM file that allows PCB manufacturers like JLCPCB to auto populate all SMT components on these boards when they manufacture them? JLCPCB apparently provides this service.
Thanks for this awesome project!!

**Comment by aerobaticant** [comment]
If you open the project in KiCad you can use **Tools->Generate Bill of Materials** in Eeschema (schematic editor).
All the part numbers are there.

I have now added the CSV file to the repo. :-)
